### ISSUE TITLE
settings: serverside email validation error

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#25]
i was allowed to change my email from bryce_aebi@brown.edu to bryce_aebi@brownedu

**Comment by jbowens** [comment]
We're using [validate_emal](https://pypi.python.org/pypi/validate_email) to validate emails. They, for whatever reason, don't require a period in the hostname... Maybe in case you're using email in an intranet for something? Anyways, if we really care about this, we can install pyDNS and then use `validate_email`'s `check_mx` option which will ensure that the host is actually valid rather than just a string that looks like a hostname.
